### ISSUE TITLE
cannot use templateUrl

### ISSUE THREAD

**Issue by stefanwatt** [hiepxanh/angular-vite-example#1]
Using a templateUrl instead of a templateString results in the following error.

```
error_handler.ts:45 ERROR Error: Uncaught (in promise): Error: Component 'FooComponent' is not resolved:
 - templateUrl: ./foo.component.html
 - styleUrls: ["./foo.component.css"]
Did you run and wait for 'resolveComponentResources()'?
```

**Comment by MarioGeier00** [comment]
Same problem here!
It's probably a missing configuration for vite to resolve the URL properly

**Comment by Hova25** [comment]
Hello , i have the save problem, do you have find a solution to use templateUrl ?

**Comment by NguyenTheLuan** [comment]
I got the same problem. Do you have any idea or what is root cause?

![image](https://user-images.githubusercontent.com/73965057/235668977-d006281f-867f-404e-80dd-e8b2ce41402e.png)

**Comment by MarioGeier00** [comment]
Maybe wait until Angular 16 is released, it should come with integrated vite support.

**Comment by dgmachado** [comment]
I'm having the same issue. has anyone solved this problem?

**Comment by lolojur** [comment]
I've tried too and I have the same issue.
Component are not resolved during the initialisation.

**Comment by hiepxanh** [comment]
To support selector matching, the Angular compiler needs to maintain a dependency graph between your components which requires a different compilation model than Vite. So it is basicly cannot use templateUrl file. BUT....


[https://blog.angular.io/angular-v16-is-here-4d7a28ec680d](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d)

You can give Vite + esbuild a try by updating your angular.json:

``` 

...
"architect": {
  "build": {                     /* Add the esbuild suffix  */
    "builder": "@angular-devkit/build-angular:browser-esbuild",
...


```


Simple and easy, cheer!
